apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-app
  template:
    metadata:
      labels:
        app: car-app
    spec:
      containers:
        - name: car-app
          image: kubernetes-test-app:latest
          ports:
            - containerPort: 8000


