name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests (if you create test files later)
      - name: Run tests
        run: |
          echo "No tests yet"
      
      # Step 5: Build Docker image
      - name: Build Docker image
        run: docker build -t car-price-app1:latest .

      # Step 6: Log in to DockerHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 7: Push image to Docker Hub
      - name: Push to Docker Hub
        run: |
          docker tag car-price-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/car-price-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/car-price-app:latest
